# Generated by Django 5.2 on 2025-04-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0004_governmentschemes_scheme_name_hindi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentschemes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
